### ISSUE TITLE
UI Implemention of the Patient Summary Views

### ISSUE THREAD

**Issue by yassinedorbozgithub** [jembi/smart-health-links-portal#35]
### Progress ~100%
_Resource Type_| _Status_ | _PR(s)_ | Approved by
--- | --- | --- | --- |
**Patient** | :heavy_check_mark: Done | #19<br>#27 | @BMartinos, @jacob-khoza-symb <br>@BMartinos, @jacob-khoza-symb |
**Organization** | :heavy_check_mark: Done | #32 | @yassinedorbozgithub |
**Condition** | :heavy_check_mark: Done | #36 | @yassinedorbozgithub |
**Practitioner** | :heavy_check_mark: Done | #43 | @yassinedorbozgithub |
**Medication<br/>Composition<br/>Immunization<br/>observation** | :heavy_check_mark: Done | #58 | @amalessid, @BMartinos |
**Allergy Intolerance** | :heavy_check_mark: Done | #46 | @amalessid , @BMartinos

### Sub-tasks
- [x] Patient
- [x] Practitioner
- [x] Organization
- [x] Condition
- [x] AllergyIntolerance
- [x] Medication
- [x] Composition 
- [x] Immunization
- [x] Observation

**NB**: The number of sub-tasks can be increased based on the number of resource types per patient summary data.

### Useful links
https://github.com/jddamore/IPSviewer/tree/main/samples
https://ps-ca-renderer.apibox.ca/index.html

**Comment by amalessid** [comment]
Thanks for the initiative @yassinedorbozgithub :raised_hands: :rocket:

**Comment by yassinedorbozgithub** [comment]
All sub-tasks mentioned in this issue are done :heavy_check_mark:
